name: tests

on:
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 17.x]

    steps:
      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --include-dev

      - name: Run the tests
        run: npm test

      - run: bun install
      - run: bun test
